name: CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Build and test ${{ matrix.os }} ${{ matrix.arch }} ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        go-version: ['1.22', '1.23']
        exclude:
          - os: windows
            arch: arm64
    env:
      VAULT_VERSION: "1.14.0"
      VAULT_TOKEN: "root"
      VAULT_ADDR: "http://127.0.0.1:8200"
    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Vendor Go Modules
        run: make vendor

      - name: Ensure clean working tree
        run: git diff --exit-code

      - name: Build ${{ matrix.os }}
        if: matrix.os != 'windows'
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o sops-${{ matrix.go-version }}-${{ matrix.os }}-${{ matrix.arch }}-${{ github.sha }} -v ./cmd/sops

      - name: Build ${{ matrix.os }}
        if: matrix.os == 'windows'
        run: GOOS=${{ matrix.os }} go build -o sops-${{ matrix.go-version }}-${{ matrix.os }}-${{ github.sha }} -v ./cmd/sops

      - name: Import test GPG keys
        run: for i in 1 2 3 4 5; do gpg --import pgp/sops_functional_tests_key.asc && break || sleep 15; done

      - name: Test
        run: make test

      - name: Upload artifact for ${{ matrix.os }}
        if: matrix.os != 'windows'
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: sops-${{ matrix.go-version }}-${{ matrix.os }}-${{ matrix.arch }}-${{ github.sha }}
          path: sops-${{ matrix.go-version }}-${{ matrix.os }}-${{ matrix.arch }}-${{ github.sha }}

      - name: Upload artifact for ${{ matrix.os }}
        if: matrix.os == 'windows'
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: sops-${{ matrix.go-version }}-${{ matrix.os }}-${{ github.sha }}
          path: sops-${{ matrix.go-version }}-${{ matrix.os }}-${{ github.sha }}
  test:
    name: Functional tests
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        go-version: ['1.22']
    env:
      VAULT_VERSION: "1.14.0"
      VAULT_TOKEN: "root"
      VAULT_ADDR: "http://127.0.0.1:8200"
    steps:
      - name: Check out code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      # Rustup will detect toolchain version and profile from rust-toolchain.toml
      # It will download and install the toolchain and components automatically
      # and make them available for subsequent commands
      - name: Install Rust toolchain
        run: rustup show

      - name: Show Rust version
        run: cargo --version

      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: sops-${{ matrix.go-version }}-linux-amd64-${{ github.sha }}

      - name: Move SOPS binary
        run: mv sops-${{ matrix.go-version }}-linux-amd64-${{ github.sha }} ./functional-tests/sops

      - name: Make SOPS binary executable
        run: chmod +x ./functional-tests/sops

      - name: Download Vault
        run: curl -O "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip" && sudo unzip vault_${VAULT_VERSION}_linux_amd64.zip -d /usr/local/bin/

      - name: Start Vault server
        run: vault server -dev -dev-root-token-id="$VAULT_TOKEN" &

      - name: Enable Vault KV
        run: vault secrets enable -version=1 kv

      - name: Import test GPG keys
        run: for i in 1 2 3 4 5; do gpg --import pgp/sops_functional_tests_key.asc && break || sleep 15; done

      - name: Run tests
        run: cargo test
        working-directory: ./functional-tests

  # The 'check' job should depend on all other jobs so it's possible to configure branch protection only for 'check'
  # instead of having to explicitly list all individual jobs that need to pass.
  check:
    if: always()

    needs:
      - build
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          allowed-failures: docs, linters
          allowed-skips: non-voting-flaky-job
          jobs: ${{ toJSON(needs) }}
